# Generated by Django 2.0.2 on 2018-02-21 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('players', models.TextField()),
                ('lobpass', models.CharField(max_length=200)),
                ('ltype', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=200)),
                ('administrator', models.CharField(max_length=200)),
                ('gamemode', models.CharField(max_length=200)),
                ('lstatus', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('moneybet', models.IntegerField()),
                ('playerscores', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Trivia Lobbies',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_a', models.TextField()),
                ('equipo_b', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Polla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PollaApuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apuesta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PollaPartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador', models.TextField()),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='PollaPuntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('id_pollaapuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.PollaApuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='pollaapuesta',
            name='id_polla_partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.PollaPartido'),
        ),
        migrations.AddField(
            model_name='pollaapuesta',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.User'),
        ),
    ]
