# Generated by Django 2.0.2 on 2018-02-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollaapuesta',
            old_name='id_polla_partido',
            new_name='polla_partido',
        ),
        migrations.RenameField(
            model_name='pollaapuesta',
            old_name='id_user',
            new_name='user',
        ),
    ]
