# Generated by Django 2.0.2 on 2018-02-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollapartido',
            name='id_polla',
        ),
    ]
