# Generated by Django 2.0.2 on 2018-02-12 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0004_answers_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='trivialobbys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('players', models.CharField(max_length=200)),
                ('lobpass', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Trivia Lobbys',
            },
        ),
    ]
