# Generated by Django 2.0.2 on 2018-02-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0004_answers_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_a', models.TextField()),
                ('equipo_b', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Polla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador', models.TextField()),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='PollaApuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apuesta', models.TextField()),
                ('id_polla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.Polla')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.users')),
            ],
        ),
    ]
