# Generated by Django 2.0.2 on 2018-02-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0005_trivialobbys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trivialobbys',
            new_name='trivialobbies',
        ),
        migrations.AlterModelOptions(
            name='trivialobbies',
            options={'verbose_name_plural': 'Trivia Lobbies'},
        ),
    ]
