# Generated by Django 2.0.2 on 2018-02-13 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0006_auto_20180212_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='lobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('players', models.CharField(max_length=200)),
                ('lobpass', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Trivia Lobbies',
            },
        ),
        migrations.DeleteModel(
            name='trivialobbies',
        ),
    ]
