# Generated by Django 2.0.2 on 2018-02-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0007_auto_20180213_0048'),
        ('mundialitisapps', '0005_partido_polla_pollaapuesta'),
    ]

    operations = [
    ]
