# Generated by Django 2.0.2 on 2018-02-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0007_auto_20180213_0048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='lobbies',
            new_name='Lobby',
        ),
        migrations.RenameModel(
            old_name='questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
