# Generated by Django 2.0.2 on 2018-02-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0008_auto_20180213_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='administrator',
            field=models.CharField(default='pepe', max_length=200),
            preserve_default=False,
        ),
    ]
