# Generated by Django 2.0.2 on 2018-02-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0009_lobby_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='players',
            field=models.TextField(),
        ),
    ]
