# Generated by Django 2.0.2 on 2018-02-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0010_auto_20180216_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='gamemode',
            field=models.CharField(default='Difícil', max_length=200),
            preserve_default=False,
        ),
    ]
