# Generated by Django 2.0.2 on 2018-02-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0011_lobby_gamemode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='status',
            new_name='ltype',
        ),
    ]
