# Generated by Django 2.0.2 on 2018-02-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0009_teams_players_data'),
        ('mundialitisapps', '0012_auto_20180219_0318'),
    ]

    operations = [
    ]
