# Generated by Django 2.0.2 on 2018-02-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0013_lobby_lstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='moneybet',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lobby',
            name='playerscores',
            field=models.TextField(default='Pepe: 50'),
            preserve_default=False,
        ),
    ]
