# Generated by Django 2.0.2 on 2018-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0014_auto_20180219_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='winner',
            field=models.CharField(default='Pepe', max_length=200),
            preserve_default=False,
        ),
    ]
