# Generated by Django 2.0.2 on 2018-02-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0016_auto_20180221_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_a', models.TextField()),
                ('equipo_b', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Polla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PollaApuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apuesta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PollaPartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador', models.TextField()),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='PollaPuntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.User')),
            ],
        ),
        migrations.AddField(
            model_name='pollaapuesta',
            name='polla_partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.PollaPartido'),
        ),
        migrations.AddField(
            model_name='pollaapuesta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundialitisapps.User'),
        ),
    ]
