# Generated by Django 2.0.2 on 2018-02-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0020_partido_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['id'], 'verbose_name_plural': 'Partidos'},
        ),
    ]
