# Generated by Django 2.0.2 on 2018-02-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundialitisapps', '0021_auto_20180225_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polla',
        ),
        migrations.RemoveField(
            model_name='pollaapuesta',
            name='polla_partido',
        ),
        migrations.RemoveField(
            model_name='pollaapuesta',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pollapartido',
            name='id_partido',
        ),
        migrations.RemoveField(
            model_name='pollapuntaje',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='lobby',
            options={'ordering': ['id'], 'verbose_name_plural': 'Trivia Lobbies'},
        ),
        migrations.DeleteModel(
            name='PollaApuesta',
        ),
        migrations.DeleteModel(
            name='PollaPartido',
        ),
        migrations.DeleteModel(
            name='PollaPuntaje',
        ),
    ]
