insert into mundialitisapps_partido VALUES (DEFAULT, 'Rusia' , 'Arabia Saudita');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Egipto' , 'Uruguay');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Marruecos' , 'Irán');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Portugal' , 'España');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Francia' , 'Australia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Argentina' , 'Islandia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Perú' , 'Dinamarca');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Croacia' , 'Nigeria');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Costa Rica' , 'Serbia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Alemania' , 'México');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Brasil' , 'Suiza');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Suecia' , 'República de Corea');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Bélgica' , 'Panamá');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Túnez' , 'Inglaterra');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Colombia' , 'Japón');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Polonia' , 'Senegal');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Rusia' , 'Egipto');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Portugal' , 'Marruecos');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Uruguay' , 'Arabia Saudita');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Irán' , 'España');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Dinamarca' , 'Australia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Francia' , 'Perú');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Argentina' , 'Croacia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Brasil' , 'Costa Rica');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Nigeria' , 'Islandia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Serbia' , 'Suiza');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Bélgica' , 'Túnez');
insert into mundialitisapps_partido VALUES (DEFAULT, 'República de Corea' , 'México');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Alemania' , 'Suecia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Inglaterra', 'Panamá');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Japón' , 'Senegal');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Polonia' , 'Colombia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Uruguay' , 'Rusia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Arabia Saudita' , 'Egipto');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Irán' , 'Portugal');
insert into mundialitisapps_partido VALUES (DEFAULT, 'España' , 'Marruecos');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Dinamarca' , 'Francia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Australia' , 'Perú');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Nigeria' , 'Argentina');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Islandia' , 'Croacia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'México' , 'Suecia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'República de Corea', 'Alemania');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Serbia' , 'Brasil');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Suiza' , 'Costa Rica');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Japón' , 'Polonia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Senegal' , 'Colombia');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Panamá' , 'Túnez');
insert into mundialitisapps_partido VALUES (DEFAULT, 'Inglaterra' , 'Bélgica');
