"""
Django settings for Mundialitis project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*9sy7cb@@y00h!+)2lkdnvd5fo32bozz18@ddde5ne$nupi@nn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#Local
#ALLOWED_HOSTS = []
#Heroku

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'mundialitis.herokuapp.com', 'mundialitis2.herokuapp.com', 'asdaas.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'mundialitisapps',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#MIDDLEWARE_CLASSES = (
#    # Simplified static file serving.
#    # https://warehouse.python.org/project/whitenoise/
#    'whitenoise.middleware.WhiteNoiseMiddleware',)

ROOT_URLCONF = 'Mundialitis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mundialitis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

#Local
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'mundialitis',
#        'USER': 'postgres',
#       'PASSWORD': '123456789',
 #       'HOST': '127.0.0.1',
 #       'PORT': '5432',
 #   }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'HOST':"ec2-184-73-202-79.compute-1.amazonaws.com",
        'NAME': 'db1aa0cr8ljno7',
        'USER': 'mgsortilinjdlj',
        'PASSWORD': 'da6fa26998b4c68493b36a9f04983e7fea84e3853553f4f47a200fe865532bae',

        'PORT': 5432


    }

}

import dj_database_url
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)
#Heroku
#DATABASES = {
#    'default': dj_database_url.config()
#}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

#Local
STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
#Heroku
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)
